"use client";

import { useState, useEffect, useCallback } from "react";
import { Coffee, Loader2, Copy, Check, Calendar } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { format } from "date-fns";

type Briefing = {
  id: string;
  briefing_text: string;
  created_at: string;
};

export default function BriefingPage() {
  const router = useRouter();
  const [briefings, setBriefings] = useState<Briefing[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [latestBriefing, setLatestBriefing] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  const fetchBriefings = useCallback(async () => {
    try {
      const response = await fetch("/api/briefing");
      const data = await response.json();
      if (response.ok) {
        setBriefings(data);
        if (data.length > 0 && !latestBriefing) {
          setLatestBriefing(data[0].briefing_text);
        }
      }
    } catch (err) {
      console.error("Failed to fetch briefings", err);
    }
  }, [latestBriefing]);

  useEffect(() => {
    async function checkAccess() {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        router.push("/login");
        return;
      }

      const { data: profile } = await supabase
        .from("profiles")
        .select("subscribed")
        .eq("id", user.id)
        .single();

      if (!profile?.subscribed) {
        router.push("/pricing?message=subscribe");
        return;
      }

      const planRes = await fetch("/api/user-plan");
      const { plan } = await planRes.json();
      
      if (plan === "starter" || plan === "plus") {
        router.push("/pricing?message=upgrade-pro");
        return;
      }
      
      await fetchBriefings();
      setIsLoading(false);
    }
    checkAccess();
  }, [router, fetchBriefings]);

  async function handleGenerate() {
    setIsGenerating(true);
    setError("");
    setLatestBriefing(null);

    try {
      const response = await fetch("/api/briefing", { method: "POST" });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to generate briefing");

      setLatestBriefing(data.briefingText);
      await fetchBriefings();
    } catch (err) {
      setError("Something went wrong. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  }

  function copyToClipboard() {
    if (!latestBriefing) return;
    navigator.clipboard.writeText(latestBriefing);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  if (isLoading) {
    return (
      <div style={{ minHeight: "100vh", backgroundColor: "#F8FAFC", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <Loader2 className="animate-spin text-[#0A1628]" size={48} />
      </div>
    );
  }

  return (
    <div style={{ maxWidth: "900px", margin: "0 auto", padding: "40px 48px", backgroundColor: "white", fontFamily: "system-ui, -apple-system, sans-serif" }}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 300px", gap: "32px", alignItems: "start" }}>
      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        <div style={{ backgroundColor: "white", borderRadius: "12px", padding: "32px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "20px" }}>
              <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                <Coffee size={32} color="#0A1628" style={{ display: "block", marginBottom: "8px" }} />
                <h1 style={{ fontSize: "28px", fontWeight: "800", color: "#0A1628", margin: 0 }}>
                  AI Daily Market Briefing
                </h1>
                <p style={{ color: "#64748B", margin: 0 }}>
                  Get your professional morning briefing generated by AI.
                </p>
              </div>
              <div style={{ flex: "1 1 300px" }}>
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  style={{
                    backgroundColor: "#0A1628",
                    color: "white",
                    padding: "14px 28px",
                    borderRadius: "8px",
                    fontSize: "15px",
                    fontWeight: "600",
                    border: "none",
                    cursor: isGenerating ? "not-allowed" : "pointer",
                    width: "100%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: "10px",
                    opacity: isGenerating ? 0.7 : 1
                  }}
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="animate-spin" size={18} />
                      Generating Briefing...
                    </>
                  ) : (
                    "Generate Today's Briefing"
                  )}
                </button>
              </div>
            </div>

            {error && (
              <div style={{ padding: "16px", backgroundColor: "#FEF2F2", border: "1px solid #FEE2E2", borderRadius: "8px", color: "#991B1B", fontSize: "14px" }}>
                {error}
              </div>
            )}

            {latestBriefing ? (
              <div style={{ display: "flex", flexDirection: "column", gap: "24px", paddingTop: "24px", borderTop: "1px solid #E5E7EB" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <h3 style={{ fontSize: "12px", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.1em", color: "#64748B", margin: 0 }}>
                    Today&apos;s Insight
                  </h3>
                  <button
                    onClick={copyToClipboard}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "8px",
                      padding: "8px 16px",
                      backgroundColor: "#F8FAFC",
                      border: "1px solid #E5E7EB",
                      borderRadius: "6px",
                      fontSize: "13px",
                      fontWeight: "600",
                      color: "#0A1628",
                      cursor: "pointer"
                    }}
                  >
                    {copied ? (
                      <>
                        <Check size={16} />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy size={16} />
                        Copy Briefing
                      </>
                    )}
                  </button>
                </div>
                <div style={{ 
                  backgroundColor: "white", 
                  borderRadius: "12px", 
                  padding: "32px", 
                  boxShadow: "0 1px 3px rgba(0,0,0,0.1)", 
                  lineHeight: "1.8",
                  color: "#1E293B",
                  maxHeight: "700px",
                  overflowY: "auto"
                }}>
                  {latestBriefing.split('\n').map((line, i) => (
                    <p key={i} style={{ 
                      marginBottom: "16px",
                      fontWeight: line.startsWith('SECTION') ? "800" : "normal",
                      fontSize: line.startsWith('SECTION') ? "18px" : "15px",
                      marginTop: line.startsWith('SECTION') ? "32px" : "0",
                      color: line.startsWith('SECTION') ? "#0A1628" : "#334155",
                      borderBottom: line.startsWith('SECTION') ? "1px solid #E5E7EB" : "none",
                      paddingBottom: line.startsWith('SECTION') ? "8px" : "0"
                    }}>
                      {line}
                    </p>
                  ))}
                </div>
              </div>
            ) : !isGenerating && (
              <div style={{ 
                padding: "80px 40px", 
                textAlign: "center", 
                border: "2px dashed #E5E7EB", 
                borderRadius: "12px", 
                display: "flex", 
                flexDirection: "column", 
                gap: "16px", 
                alignItems: "center" 
              }}>
                <div style={{ padding: "16px", borderRadius: "50%", backgroundColor: "#F8FAFC", color: "#0A1628" }}>
                  <Coffee size={40} />
                </div>
                <p style={{ color: "#64748B", maxWidth: "320px", margin: "0 auto", fontSize: "15px" }}>
                  Click the button above to generate your first AI market briefing.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        <h3 style={{ 
          fontSize: "12px", 
          fontWeight: "800", 
          textTransform: "uppercase", 
          letterSpacing: "0.1em", 
          color: "#64748B", 
          display: "flex", 
          flexDirection: "column", 
          gap: "8px", 
          margin: 0 
        }}>
          <Calendar size={20} style={{ display: "block" }} />
          Past Briefings
        </h3>
        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          {briefings.length > 0 ? (
            briefings.map((b) => (
              <button
                key={b.id}
                onClick={() => setLatestBriefing(b.briefing_text)}
                style={{
                  padding: "16px",
                  borderRadius: "12px",
                  border: latestBriefing === b.briefing_text ? "2px solid #0A1628" : "1px solid #E5E7EB",
                  backgroundColor: latestBriefing === b.briefing_text ? "#F8FAFC" : "white",
                  textAlign: "left",
                  transition: "all 0.2s ease",
                  cursor: "pointer",
                  display: "flex",
                  flexDirection: "column",
                  gap: "4px"
                }}
              >
                <div style={{ fontWeight: "700", color: "#0A1628", fontSize: "14px" }}>
                  {format(new Date(b.created_at), "EEEE, dd MMM yyyy")}
                </div>
                <div style={{ fontSize: "12px", color: "#64748B" }}>
                  {format(new Date(b.created_at), "HH:mm")}
                </div>
              </button>
            ))
          ) : (
            <p style={{ fontSize: "13px", color: "#94A3B8", fontStyle: "italic", margin: 0 }}>
              No history available yet.
            </p>
          )}
        </div>
      </div>
      </div>
    </div>
  );
}
