"use client";

import { useState, useEffect, useCallback } from "react";
import { Coffee, Loader2, Copy, Check, Calendar } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { format } from "date-fns";

type Briefing = {
  id: string;
  briefing_text: string;
  created_at: string;
};

export default function BriefingPage() {
  const router = useRouter();
  const [briefings, setBriefings] = useState<Briefing[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [latestBriefing, setLatestBriefing] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [userEmail, setUserEmail] = useState<string | undefined>();
  const [copied, setCopied] = useState(false);

  const fetchBriefings = useCallback(async () => {
    try {
      const response = await fetch("/api/briefing");
      const data = await response.json();
      if (response.ok) {
        setBriefings(data);
        if (data.length > 0 && !latestBriefing) {
          setLatestBriefing(data[0].briefing_text);
        }
      }
    } catch (err) {
      console.error("Failed to fetch briefings", err);
    }
  }, [latestBriefing]);

  useEffect(() => {
    async function checkAccess() {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        router.push("/login");
        return;
      }

      setUserEmail(user.email);

      const { data: profile } = await supabase
        .from("profiles")
        .select("subscribed")
        .eq("id", user.id)
        .single();

      if (!profile?.subscribed) {
        router.push("/pricing?message=subscribe");
        return;
      }

      // Check if user has Pro plan
      const planRes = await fetch("/api/user-plan");
      const { plan } = await planRes.json();
      
      if (plan === "starter" || plan === "plus") {
        router.push("/pricing?message=upgrade-pro");
        return;
      }
      
      await fetchBriefings();
      setIsLoading(false);
    }
    checkAccess();
  }, [router, fetchBriefings]);

  async function handleGenerate() {
    setIsGenerating(true);
    setError("");
    setLatestBriefing(null);

    try {
      const response = await fetch("/api/briefing", { method: "POST" });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to generate briefing");

      setLatestBriefing(data.briefingText);
      await fetchBriefings();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setIsGenerating(false);
    }
  }

  function copyToClipboard() {
    if (!latestBriefing) return;
    navigator.clipboard.writeText(latestBriefing);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#0a1628] flex items-center justify-center">
        <Loader2 className="animate-spin text-[#c1a362]" size={48} />
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
            <div className="lg:col-span-2 stack gap-6">
              <div className="card shadow-xl overflow-hidden border border-[rgba(193,163,98,0.2)]">
                <div className="p-8 stack gap-6">
                  <div className="flex justify-between items-start">
                    <div className="stack gap-2">
                      <h2 className="text-2xl font-bold flex items-center gap-2">
                        <Coffee className="text-[#c1a362]" />
                        AI Daily Market Briefing
                      </h2>
                      <p className="text-gray-400">
                        Get your professional morning briefing generated by AI.
                      </p>
                    </div>
                    <button
                      className="btn"
                      onClick={handleGenerate}
                      disabled={isGenerating}
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="animate-spin" size={18} />
                          Generating...
                        </>
                      ) : (
                        "Generate Today's Briefing"
                      )}
                    </button>
                  </div>

                  {error && <div className="alert alert-error">{error}</div>}

                  {latestBriefing ? (
                    <div className="stack gap-6 fade-in">
                      <div className="flex justify-between items-center pt-6 border-t border-[rgba(193,163,98,0.1)]">
                        <h3 className="text-lg font-bold uppercase tracking-widest text-[#c1a362] text-xs">Today&apos;s Insight</h3>
                        <button
                          className="btn-light btn-sm flex items-center gap-2"
                          onClick={copyToClipboard}
                        >
                          {copied ? (
                            <>
                              <Check size={16} />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy size={16} />
                              Copy Briefing
                            </>
                          )}
                        </button>
                      </div>
                      <div className="p-8 rounded-xl bg-white text-gray-900 shadow-inner max-h-[700px] overflow-y-auto">
                        {latestBriefing.split('\n').map((line, i) => (
                          <p key={i} className={`mb-4 leading-relaxed ${line.startsWith('SECTION') ? 'font-bold text-lg mt-8 mb-4 text-[#0a1628] border-b-2 border-[#c1a362] pb-1 inline-block' : ''}`}>
                            {line}
                          </p>
                        ))}
                      </div>
                    </div>
                  ) : !isGenerating && (
                    <div className="py-20 text-center border border-dashed border-[rgba(193,163,98,0.2)] rounded-xl stack gap-4 items-center">
                      <div className="p-4 rounded-full bg-[rgba(193,163,98,0.05)] text-[#c1a362]">
                        <Coffee size={40} />
                      </div>
                      <p className="text-gray-500 max-w-xs mx-auto">Click the button above to generate your first AI market briefing.</p>
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div className="stack gap-6">
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#c1a362] flex items-center gap-2">
                <Calendar size={16} />
                Past Briefings
              </h3>
              <div className="stack gap-3">
                {briefings.length > 0 ? (
                  briefings.map((b) => (
                    <button
                      key={b.id}
                      onClick={() => setLatestBriefing(b.briefing_text)}
                      className={`p-4 rounded-xl border text-left transition-all ${
                        latestBriefing === b.briefing_text
                          ? "bg-[rgba(193,163,98,0.1)] border-[#c1a362] shadow-lg"
                          : "border-[rgba(193,163,98,0.1)] bg-[rgba(15,23,40,0.3)] hover:border-[#c1a362]"
                      }`}
                    >
                      <div className="font-bold text-gray-200">
                        {format(new Date(b.created_at), "EEEE, dd MMMM yyyy")}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">
                        {format(new Date(b.created_at), "HH:mm")}
                      </div>
                    </button>
                  ))
                ) : (
                  <p className="text-xs text-gray-500 italic">No history available yet.</p>
                )}
              </div>
            </div>
          </div>
  );
}
