import { TopNav } from "@/components/top-nav";

const termsSections = [
  {
    title: "1. About Suitance",
    content:
      "Suitance is a software-as-a-service drafting tool operated as an independent technology business. Suitance is not authorised or regulated by the Financial Conduct Authority (FCA). Suitance does not hold, nor does it require, FCA authorisation because it does not carry on regulated activities as defined under the Financial Services and Markets Act 2000 (FSMA 2000). Suitance provides software that assists FCA-authorised financial advisers and paraplanners in drafting suitability report documents. The generation of a draft document by Suitance does not constitute a personal recommendation, financial advice, investment advice, or any other regulated activity within the meaning of FSMA 2000 or the FCA Handbook. Users of Suitance remain solely responsible for ensuring that all advice they give to their clients complies with applicable FCA rules, including but not limited to COBS 9 (Suitability), COBS 9A, and the Consumer Duty rules set out in PRIN 2A of the FCA Handbook.",
  },
  {
    title: "Regulatory Status and Limitations",
    content:
      "Suitance Limited is a software technology company. We are not authorised or regulated by the Financial Conduct Authority (FCA), the Australian Securities and Investments Commission (ASIC), the Securities and Exchange Commission (SEC), or any other financial regulatory body. Our software is designed to assist regulated financial advisers in drafting documents but does not constitute regulated financial advice. Users of Suitance are solely responsible for ensuring all advice given to clients meets applicable regulatory requirements. All AI-generated content must be reviewed and approved by a suitably qualified and regulated individual before use.",
  },
  {
    title: "2. Permitted Users",
    content:
      "Suitance is intended exclusively for use by individuals who are either: (a) directly authorised by the FCA and hold the appropriate permissions to give investment advice; or (b) employed by or acting under the supervision of an FCA-authorised firm with appropriate permissions. By creating an account you confirm that you fall within one of these categories. Suitance reserves the right to suspend or terminate accounts where this condition is not met.",
  },
  {
    title: "3. Adviser Responsibility and No Advice",
    content:
      "All content generated by Suitance is a draft only. It must be independently reviewed, verified for accuracy, amended where necessary, and approved by a suitably qualified and FCA-authorised individual before being provided to any client. The adviser or paraplanner who reviews and approves the report is solely responsible for its content, accuracy, suitability, and regulatory compliance. Suitance does not verify the accuracy of information input by users. The quality and compliance of any final report depends entirely on the accuracy of information provided and the professional judgement of the reviewing adviser. Nothing generated by Suitance should be treated as a substitute for professional expertise, independent judgement, or compliance review.",
  },
  {
    title: "4. Limitation of Liability",
    content:
      "To the fullest extent permitted by applicable law, Suitance excludes all liability for any loss, damage, regulatory action, FCA investigation, Financial Ombudsman Service determination, fine, penalty, claim, or any other consequence arising directly or indirectly from: (a) use of content generated by this platform; (b) reliance on any draft report without appropriate professional review; (c) errors, omissions, or inaccuracies in generated content; or (d) failure of any generated content to comply with FCA rules or any other applicable regulation. This limitation applies whether or not the content has been reviewed or amended prior to use. Nothing in these terms excludes liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded under English law.",
  },
  {
    title: "5. Data Protection and UK GDPR",
    content:
      "Suitance processes personal data in accordance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018 (DPA 2018). By using Suitance, you confirm that: (a) you have obtained all necessary lawful bases under UK GDPR Article 6 to process the personal data of clients whose information you input into this platform; (b) where client data constitutes special category data under UK GDPR Article 9 (which may include data about health, financial vulnerability, or other sensitive characteristics), you have identified and documented the appropriate condition for processing; (c) you have provided your clients with appropriate transparency information under UK GDPR Articles 13 and 14 about how their data is processed, including its use in AI-assisted drafting tools. Suitance acts as a data processor in respect of client personal data you input. Suitance stores data securely using industry-standard encryption. Suitance does not sell, share, or transfer personal data to third parties except where required by law or as necessary to provide the service (such as use of AI model providers). Client data is not used to train AI models. Data is retained for as long as your account remains active and for a reasonable period thereafter for backup and legal purposes. You may request deletion of your data by contacting us.",
  },
  {
    title: "6. Intellectual Property",
    content:
      "The Suitance platform, its design, software, and underlying technology are the intellectual property of Suitance. Draft reports generated using your input data are provided to you for your professional use. Suitance does not claim ownership of report content generated from your input.",
  },
  {
    title: "7. Subscription and Payment",
    content:
      "Access to Suitance is provided on a subscription basis. Payment is processed securely by Stripe. Subscription fees are charged monthly in advance. You may cancel your subscription at any time through the customer portal. Cancellation takes effect at the end of the current billing period. No refunds are provided for unused portions of a billing period. Suitance reserves the right to change subscription pricing with reasonable notice.",
  },
  {
    title: "8. Acceptable Use",
    content:
      "Suitance may only be used for lawful purposes in connection with legitimate financial advisory activities. You must not use Suitance to generate documents intended to mislead clients, regulators, or any other party. You must not attempt to reverse engineer, copy, resell, or sublicense the Suitance platform or its outputs without written permission. Suitance reserves the right to suspend or terminate accounts that breach these terms without notice.",
  },
  {
    title: "9. Changes to These Terms",
    content:
      "Suitance may update these terms from time to time to reflect changes in law, regulation, or the service. Material changes will be notified to users by email or by notice within the platform. Continued use of the platform following notification of changes constitutes acceptance of the updated terms.",
  },
  {
    title: "10. Governing Law",
    content:
      "These terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.",
  },
];

export default function TermsPage() {
  return (
    <main className="landing-page">
      <section className="landing-hero">
        <div className="shell">
          <TopNav />

          <div className="stack fade-in" style={{ position: "relative", zIndex: 1 }}>
            <span className="section-kicker">Legal</span>
            <h1 className="display-title" style={{ fontSize: "clamp(2.4rem, 6vw, 4.4rem)" }}>
              Terms of Use
            </h1>
            <p className="hero-subtitle" style={{ maxWidth: 820 }}>
              Last updated: May 2026
            </p>
          </div>
        </div>
      </section>

      <section className="section-block shell">
        <div className="card stack" style={{ gap: 26 }}>
          {termsSections.map((section) => (
            <article key={section.title} className="stack" style={{ gap: 10 }}>
              <h2 className="section-title" style={{ fontSize: "1.35rem" }}>
                {section.title}
              </h2>
              <p className="muted" style={{ margin: 0, fontSize: "1rem", lineHeight: 1.8 }}>
                {section.content}
              </p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
