import { TopNav } from "@/components/top-nav";

const termsSections = [
  {
    title: "1. Nature of Service",
    content:
      "Suitance is a software drafting tool designed to assist FCA-authorised financial advisers in preparing suitability report drafts. Suitance is not authorised or regulated by the Financial Conduct Authority. Suitance does not provide financial advice, investment advice, or any form of regulated activity as defined by the Financial Services and Markets Act 2000.",
  },
  {
    title: "2. Adviser Responsibility",
    content:
      "All content generated by Suitance must be reviewed, verified, and where necessary amended by a suitably qualified and FCA-authorised adviser or paraplanner before being provided to any client. The adviser firm and individual adviser are solely responsible for the suitability, accuracy, and regulatory compliance of all advice and documentation provided to their clients.",
  },
  {
    title: "3. No Liability",
    content:
      "Suitance accepts no liability whatsoever for any loss, claim, regulatory action, fine, or damage arising from the use of content generated by this platform, whether or not such content has been reviewed or amended prior to use. Use of this platform constitutes acceptance of these terms.",
  },
  {
    title: "4. Data",
    content:
      "By using Suitance you confirm you have obtained all necessary consents to process the client data you input into this platform. Suitance stores report data securely and does not share client data with third parties.",
  },
  {
    title: "5. Governing Law",
    content: "These terms are governed by the laws of England and Wales.",
  },
];

export default function TermsPage() {
  return (
    <main className="landing-page">
      <section className="landing-hero">
        <div className="shell">
          <TopNav />

          <div className="stack fade-in" style={{ position: "relative", zIndex: 1 }}>
            <span className="section-kicker">Legal</span>
            <h1 className="display-title" style={{ fontSize: "clamp(2.4rem, 6vw, 4.4rem)" }}>
              Terms of Use
            </h1>
            <p className="hero-subtitle" style={{ maxWidth: 820 }}>
              These terms explain the role of Suitance as a drafting tool and
              the responsibility retained by FCA-authorised adviser firms using
              the platform.
            </p>
          </div>
        </div>
      </section>

      <section className="section-block shell">
        <div className="card stack" style={{ gap: 26 }}>
          {termsSections.map((section) => (
            <article key={section.title} className="stack" style={{ gap: 10 }}>
              <h2 className="section-title" style={{ fontSize: "1.35rem" }}>
                {section.title}
              </h2>
              <p className="muted" style={{ margin: 0, fontSize: "1rem", lineHeight: 1.8 }}>
                {section.content}
              </p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
